FROM python:3.9 AS backend

WORKDIR /app

# 최신 pip 설치
RUN pip install --upgrade pip

# 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
EXPOSE 8000
